# intro 

In [ ]:
import numpy as np

In [5]:
array = np.array([1,2,3,4,5])

In [6]:
array

array([1, 2, 3, 4, 5])

In [7]:
array2 = np.array([1,2,3,4,5])

In [8]:
array * array2

array([ 1,  4,  9, 16, 25])

In [9]:
array.ndim

1

In [10]:
two_dim_array = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [11]:
two_dim_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
two_dim_array.ndim

2

In [13]:
array.shape


(5,)

In [14]:
two_dim_array.shape

(3, 5)

In [15]:
two_dim_array.size

15

In [16]:
two_dim_array.dtype

dtype('int32')

# converting array to diffrent type

In [17]:
float_array = array.astype('float16')

In [18]:
float_array.dtype

dtype('float16')

In [19]:
float_array

array([1., 2., 3., 4., 5.], dtype=float16)

# creating arrays

In [20]:
my_array = np.arange(1,10)

In [21]:
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
new_array = np.arange(10,21)

In [23]:
new_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
new_array.ndim

1

In [25]:
new_array.shape

(11,)

In [26]:
new_array.size

11

In [27]:
new_array.dtype

dtype('int32')

In [31]:
new_array = new_array.astype('float16')

In [32]:
new_array.dtype

dtype('float16')

In [33]:
new_array

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
      dtype=float16)

In [34]:
new_array * 2

array([20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40.],
      dtype=float16)

In [35]:
new_array

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
      dtype=float16)