In [1]:
import numpy as np

In [2]:
two_dim_array = np.arange(0,25)

In [3]:
two_dim_array = two_dim_array.reshape((5,5))

In [4]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
numbers = np.array([1,2,3,4,5])

In [6]:
numbers .mean()

3.0

In [7]:
two_dim_array.mean()

12.0

In [8]:
two_dim_array.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

In [9]:
two_dim_array.mean(axis=0)

array([10., 11., 12., 13., 14.])

In [10]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
two_dim_array.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [13]:
two_dim_array.argsort(axis=0)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]], dtype=int64)

In [14]:
two_dim_array[[0,1]] = two_dim_array[[1,0]]

In [15]:
two_dim_array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])