In [1]:
import numpy as np

In [2]:
one_dim_array = np.arange(11)

In [3]:
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
one_dim_array[0]

0

In [5]:
one_dim_array[-1]

10

In [6]:
one_dim_array[1:5]

array([1, 2, 3, 4])

In [7]:
one_dim_array[2::2]

array([ 2,  4,  6,  8, 10])

# Two dimsional indexing

In [10]:
two_dim_array = np.arange(10)


In [11]:
two_dim_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
two_dim_array.size

10

In [13]:
two_dim_array.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
two_dim_array.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
two_dim_array.reshape((2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
two_dim_array = two_dim_array.reshape((5,2))

In [17]:
two_dim_array[1:3]

array([[2, 3],
       [4, 5]])

In [18]:
two_dim_array[1:3, 0]

array([2, 4])

In [19]:
two_dim_array[::-1]

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

# Exercise 2

In [20]:
test_ar = np.arange(10,21)

In [21]:
test_ar[3]

13

In [22]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
array_2d[1][2]

6

In [24]:
sl_1d = np.arange(10)

In [25]:
sl_1d[2:6]

array([2, 3, 4, 5])

In [26]:
sl_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [29]:
array_2d[:2, 1:]

array([[2, 3],
       [5, 6]])