In [1]:
import numpy as np

# Arange

In [3]:
aray = np.arange(1,100)

In [4]:
array_decimal = np.arange(0,10,0.1)

In [5]:
array_decimal

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [6]:
array_decimal.shape

(100,)

In [7]:
array_decimal.reshape(10,10)

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

In [8]:
lin_array = np.linspace(0,5,10)

In [9]:
lin_array 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.random.randint(0,10)

3

In [13]:
np.random.rand(2,2)

array([[0.52977908, 0.83308192],
       [0.48445286, 0.57228217]])

In [14]:
new_array = np.arange(20,31)

In [15]:
new_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [16]:
new_array2 = np.arange(10,21,2)

In [17]:
new_array2 

array([10, 12, 14, 16, 18, 20])

In [24]:
mew_lin_array = np.linspace(0,1,5)

In [25]:
mew_lin_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
new_random = np.random.rand(3)

In [27]:
new_random 

array([0.26597627, 0.31951881, 0.34504813])

In [28]:
new_random2 = np.random.randint(1,10,4)

In [29]:
new_random2 

array([7, 8, 1, 9])

In [30]:
new_random .dtype

dtype('float64')